version: '2'

services:
  base:
    image: nginx:1.13.12
    volumes:
      - ./site:/usr/share/nginx/html
      - ./cert:/etc/nginx/ssl

  web-server-http1:
    extends:
      service: base
    volumes:
      - ./config/base-ssl.conf:/etc/nginx/nginx.conf
    ports:
      - "443:443"

  web-server-http2:
    extends:
      service: base
    volumes:
      - ./config/base-ssl-http2.conf:/etc/nginx/nginx.conf
    ports:
      - "444:443"

  web-server-http2-server-push:
    extends:
      service: base
    volumes:
      - ./config/base-ssl-http2-server-push.conf:/etc/nginx/nginx.conf
    ports:
      - "445:443"
